Repository esgi-insomniak/Ton-Yu-Gi-Oh, pull requests merged in 2023-07, with the labels that each got.

#65 Add exchange feature with socket
  app/client/src/helpers/api/hooks/exchange/index.ts
  app/client/src/helpers/api/hooks/users/index.ts
  app/client/src/helpers/providers/socket/SocketProvider.tsx
  app/client/src/helpers/types/socket/index.ts
  app/client/src/helpers/utils/schema/Admin/index.ts
  app/client/src/helpers/utils/schema/User/index.ts
  app/client/src/helpers/utils/schema/exchange/index.ts
  app/client/src/pages/Exchange/exchangeRoom.tsx
  app/client/src/pages/Exchange/index.tsx
  app/client/src/pages/Home.tsx
  server/gateway/src/interfaces/user-service/userExchange/user-exchange.body.dto.ts
  server/gateway/src/interfaces/websocket/socket-message/socket-message.interface.ts
  server/gateway/src/websocket.gateway.ts
  server/user-deck-service/src/controllers/user-card-set.controller.ts
  server/user-deck-service/src/services/user-card-set.service.ts
  server/user-service/src/controllers/user-exchange.controller.ts
  server/user-service/src/controllers/user-relation.controller.ts
  server/user-service/src/controllers/user.controller.ts
  server/user-service/src/services/user-exchange.service.ts
  server/user-service/src/services/user-relation.service.ts
Labels: feature

#71 Hotfix/client deck
  app/client/src/components/Decks/Deck.tsx
  app/client/src/components/Decks/DeckCard.tsx
  app/client/src/components/Decks/UserCardSets.tsx
  app/client/src/components/Layout/index.tsx
  app/client/src/helpers/api/hooks/users/index.ts
  app/client/src/helpers/types/cards/index.ts
  app/client/src/helpers/types/decks/index.ts
  app/client/src/helpers/types/users/index.ts
  app/client/src/helpers/utils/schema/User/index.ts
  app/client/src/helpers/utils/schema/cards/card-set.schema.ts
  app/client/src/pages/Decks/NewDeck.tsx
  app/client/src/pages/Decks/deck.tsx
  app/client/vite.config.ts
  server/gateway/src/controllers/cards/user-card-set.controller.ts
  server/gateway/src/interfaces/user-deck-service/userCardSet/user-card-set.interface.ts
  server/gateway/src/interfaces/user-deck-service/userCardSet/user-card-set.response.dto.ts
  server/user-deck-service/src/controllers/user-card-set.controller.ts
  server/user-deck-service/src/entities/user-deck.entity.ts
  server/user-deck-service/src/interfaces/user-card-set.interface.ts
  server/user-deck-service/src/migrations/1688374723964-migration.ts
  server/user-deck-service/src/services/user-card-set.service.ts
Labels: bug, feature

#75 Hotfix/client deck
  app/client/src/components/Booster/Booster.tsx
  app/client/src/helpers/api/hooks/booster/index.ts
  app/client/src/index.css
  app/client/src/pages/Booster/index.tsx
  app/client/src/pages/Collection/index.tsx
  app/client/src/pages/Home.tsx
Labels: bug, feature

#76 Disable adding banned cards for duels
  app/client/src/components/Decks/Deck.tsx
  app/client/src/pages/Decks/EditDeck.tsx
  app/client/src/pages/Decks/NewDeck.tsx
  server/gateway/src/controllers/cards/user-deck.controller.ts
Labels: feature

#79 fix
  app/client/src/components/Duels/HandCard.tsx
  app/client/src/components/Duels/MonsterZone.tsx
  app/client/src/pages/Exchange/exchangeRoom.tsx
Labels: bug

#82 Fix rerender socket
  app/client/src/Routes/Router.tsx
  app/client/src/components/Duels/HandCard.tsx
  app/client/src/components/Duels/MonsterZone.tsx
  app/client/src/helpers/api/hooks/auth/index.ts
  app/client/src/helpers/providers/socket/SocketProvider.tsx
  app/client/src/main.tsx
  app/client/src/pages/Duels/index.tsx
Labels: bug

#85 Add Page Exchange History
  app/client/src/Routes/Router.tsx
  app/client/src/helpers/api/hooks/admin/exchange/index.ts
  app/client/src/pages/Decks/index.tsx
  app/client/src/pages/Exchange/ExchangeHistory.tsx
  app/client/src/pages/Home.tsx
Labels: feature

#93 jean naymare 2.0
  app/client/src/components/GameCard/GameCard.tsx
  app/client/src/components/GameCard/GameCardInfos.tsx
  app/client/src/pages/Auth/Login.tsx
  app/client/src/pages/Collection/index.tsx
Labels: bug

#94 Add Auction
  app/client/src/Routes/Router.tsx
  app/client/src/components/GameCard/GameCardInfos.tsx
  app/client/src/components/Stats/index.tsx
  app/client/src/components/Timer/index.tsx
  app/client/src/helpers/api/hooks/exchange/index.ts
  app/client/src/helpers/providers/socket/SocketProvider.tsx
  app/client/src/helpers/types/auction/index.ts
  app/client/src/helpers/types/cards/index.ts
  app/client/src/pages/Auction/index.tsx
  app/client/src/pages/Booster/index.tsx
  app/client/src/pages/Collection/index.tsx
  app/client/src/pages/Decks/card.tsx
  app/client/src/pages/Home.tsx
  app/client/src/pages/Shop/previewSets.tsx
  server/gateway/src/controllers/users/user-auction-history.controller.ts
  server/gateway/src/controllers/users/user-auction.controller.ts
  server/gateway/src/interfaces/user-service/userAuction/user-auction.body.dto.ts
  server/gateway/src/interfaces/user-service/userAuction/user-auction.interface.ts
  server/gateway/src/interfaces/user-service/userAuction/user-auction.response.dto.ts
  server/gateway/src/interfaces/user-service/userAuctionHistory/user-auction-history.response.dto.ts
  server/gateway/src/interfaces/user-service/userAuctionHistory/user-auction.interface.ts
  server/gateway/src/modules/user.module.ts
  server/gateway/src/websocket.gateway.ts
  server/user-service/src/controllers/user-auction-history.controller.ts
  server/user-service/src/controllers/user-auction.controller.ts
  server/user-service/src/entities/user.entity.ts
  server/user-service/src/entities/userAuction.entity.ts
  server/user-service/src/entities/userAuctionHistory.entity.ts
  server/user-service/src/migrations/1688660430272-migration.ts
  server/user-service/src/migrations/1688668053337-migration.ts
  server/user-service/src/migrations/1688683715209-migration.ts
  server/user-service/src/migrations/1688690147396-migration.ts
  server/user-service/src/migrations/1688691544058-migration.ts
  server/user-service/src/migrations/1688695959468-migration.ts
  server/user-service/src/modules/user.module.ts
  server/user-service/src/services/user-auction-history.service.ts
  server/user-service/src/services/user-auction.service.ts
Labels: feature

#95 Feature/setup resources
  app/client/src/pages/Exchange/exchangeRoom.tsx
  app/client/src/pages/Home.tsx
  app/client/src/pages/Shop/index.tsx
  deploy/k8s/auth-service/auth-service-db.yml
  deploy/k8s/card-service/card-service-db.yml
  deploy/k8s/card-service/card-service.yml
  deploy/k8s/duel-service/duel-service-db.yml
  deploy/k8s/duel-service/duel-service.yml
  deploy/k8s/gateway/gateway.yml
  deploy/k8s/payment-service/payment-service-db.yml
  deploy/k8s/user-deck-service/user-deck-service-db.yml
  deploy/k8s/user-deck-service/user-deck-service.yml
  deploy/k8s/user-service/user-service-db.yml
  deploy/k8s/user-service/user-service.yml
  server/gateway/src/main.ts
  server/gateway/src/socket-io-adapter.ts
  server/mailer-service/src/services/mailer.service.ts
Labels: bug
