Repository esgi-insomniak/Ton-Yu-Gi-Oh, pull requests merged in 2023-06, with the labels that each got.

#37 Feature/client rework collection
  app/client/src/Routes/Router.tsx
  app/client/src/assets/css/cards/base.css
  app/client/src/components/GameCard/GameCard.tsx
  app/client/src/components/Input/index.tsx
  app/client/src/components/Layout/index.tsx
  app/client/src/helpers/api/hooks/cards/attribute.hook.ts
  app/client/src/helpers/api/hooks/cards/card-set.hook.ts
  app/client/src/helpers/api/hooks/users/index.ts
  app/client/src/helpers/utils/schema/cards/archetype.schema.ts
  app/client/src/helpers/utils/schema/cards/rarity.schema.ts
  app/client/src/pages/Collection/index.tsx
  app/client/src/pages/Shop/index.tsx
Labels: bug, feature

#39 feature(gateway): add set openning
  .env.dev.example
  .env.example
  app/client/src/helpers/utils/enum/card.ts
  app/client/src/pages/Shop/index.tsx
  app/client/src/pages/Shop/previewSets.tsx
  server/card-service/src/config/raritiesDropTable.ts
  server/card-service/src/controllers/rarity-drop-table.controller.ts
  server/card-service/src/controllers/set.controller.ts
  server/card-service/src/entities/rarity.entity.ts
  server/card-service/src/entities/rarityDropTable.entity.ts
  server/card-service/src/entities/set.entity.ts
  server/card-service/src/migrations/1687090860758-migration.ts
  server/card-service/src/modules/card.module.ts
  server/card-service/src/services/db-feeder.service.ts
  server/card-service/src/services/rarity-drop-table.service.ts
  server/card-service/src/services/set.service.ts
  server/gateway/src/controllers/cards/set.controller.ts
  server/gateway/src/controllers/cards/user-card-set.controller.ts
  server/gateway/src/controllers/cards/user-set-controller.ts
  server/gateway/src/interfaces/card-service/rarity/rarity.interface.ts
  server/gateway/src/interfaces/card-service/rarityDropTable/rarity-drop-table.interface.ts
  server/gateway/src/interfaces/card-service/set/set.interface.ts
  server/gateway/src/interfaces/card-service/set/set.response.dto.ts
  server/gateway/src/interfaces/user-deck-service/userCardSet/user-card-set.response.dto.ts
  server/gateway/src/interfaces/user-deck-service/userDeck/user-deck.response.dto.ts
  server/gateway/src/interfaces/user-deck-service/userSet/user-set.response.dto.ts
  server/user-deck-service/src/controllers/user-card-set.controller.ts
  server/user-deck-service/src/controllers/user-set.controller.ts
  server/user-deck-service/src/services/user-card-set.service.ts
Labels: feature

#40 Add test
  app/client/.gitignore
  app/client/package.json
  app/client/playwright.config.ts
  app/client/tests/auth.spec.ts
Labels: feature

#43 Feature/user relations
  app/client/package.json
  app/client/src/helpers/context/users/UserManagement.tsx
  app/client/src/helpers/providers/users/usersProvider.tsx
  app/client/src/helpers/types/socket/index.ts
  app/client/src/helpers/utils/constants.ts
  server/gateway/src/controllers/promo/promo-code.controller.ts
  server/gateway/src/interfaces/websocket/socket-emit/socket-event.interface.ts
  server/gateway/src/interfaces/websocket/socket/socket.interface.ts
  server/gateway/src/modules/websoket.module.ts
  server/gateway/src/services/guard/authorization.guard.ts
  server/gateway/src/services/guard/permission.guard.ts
  server/gateway/src/socket-io-adapter.ts
  server/gateway/src/websocket.gateway.ts
  server/user-service/src/controllers/user.controller.ts
  server/user-service/src/entities/profilePicture.entity.ts
  server/user-service/src/entities/user.entity.ts
  server/user-service/src/entities/userExchange.entity.ts
  server/user-service/src/entities/userRelation.entity.ts
  server/user-service/src/migrations/1687432805750-migration.ts
  server/user-service/src/services/user.service.ts
Labels: feature

#46 Add CardInfos Component
  app/client/src/components/GameCard/GameCard.tsx
  app/client/src/components/GameCard/GameCardInfos.tsx
  app/client/src/components/Layout/index.tsx
  app/client/src/helpers/providers/cards/cardsProvider.tsx
  app/client/src/helpers/types/cards/index.ts
  app/client/src/pages/Collection/index.tsx
  app/client/src/pages/Shop/previewSets.tsx
Labels: feature

#51 Add modal to see card of one deck
  app/client/src/components/Decks/Deck.tsx
  app/client/src/components/GameCard/GameCard.tsx
  app/client/src/helpers/api/hooks/decks/index.ts
  app/client/src/helpers/types/decks/index.ts
  app/client/src/pages/Decks/EditDeck.tsx
  app/client/src/pages/Decks/index.tsx
  app/client/src/pages/Decks/previewDeck.tsx
  app/client/src/pages/Profile/index.tsx
  app/client/src/pages/Shop/previewSets.tsx
Labels: feature

#52 Feature/client patch promo
  app/client/src/components/Input/index.tsx
  app/client/src/helpers/api/hooks/admin/promo/index.ts
  app/client/src/helpers/api/hooks/shop/index.ts
  app/client/src/helpers/utils/schema/Admin/index.ts
  app/client/src/helpers/utils/schema/shop/index.ts
  app/client/src/pages/Admin/promos/index.tsx
  app/client/src/pages/Shop/index.tsx
Labels: feature

#53 GET Payement history OK
  app/client/src/helpers/api/hooks/admin/payement/index.ts
  app/client/src/helpers/utils/schema/Admin/index.ts
  app/client/src/pages/Admin/auth/index.tsx
  app/client/src/pages/Admin/payement/index.tsx
Labels: feature

#55 Get Logs OK
  app/client/src/helpers/api/hooks/admin/auth/index.ts
  app/client/src/helpers/utils/schema/Admin/index.ts
  app/client/src/helpers/utils/schema/Auth/index.ts
  app/client/src/pages/Admin/Layout.tsx
  app/client/src/pages/Admin/auth/index.tsx
Labels: feature

#56 Add CardSet filter on users route
  server/gateway/src/controllers/users/user.controller.ts
  server/gateway/src/interfaces/user-deck-service/userCardSet/user-card-set.query.dto.ts
  server/gateway/src/interfaces/user-service/user/user.query.dto.ts
  server/user-deck-service/src/controllers/user-card-set.controller.ts
  server/user-deck-service/src/services/user-card-set.service.ts
Labels: feature

#63 send only userId in token
  .env.dev.example
  .env.example
  server/auth-service/src/controllers/auth.controller.ts
  server/auth-service/src/controllers/token.controller.ts
  server/auth-service/src/interfaces/token/token-params.interface.ts
  server/auth-service/src/services/token.service.ts
  server/gateway/src/websocket.gateway.ts
Labels: bug
